name: Formatting

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@23.12.0
        with:
          options: "--check --diff --verbose --line-length=88"
          src: "aintelope tests"
